=== iamomin/marklogic-data-analysis-tool/data/samples/clientContent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="clientContent">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="documentId"/>
        <xs:element ref="version"/>
        <xs:element ref="previousVersionId"/>
        <xs:element ref="nextVersionId"/>
        <xs:element ref="documentName"/>
        <xs:element ref="clientContentType"/>
        <xs:element ref="fileExtension"/>
        <xs:element ref="locations"/>
        <xs:element ref="userFirstName"/>
        <xs:element ref="userLastName"/>
        <xs:element ref="authorSpaceVersion"/>
        <xs:element ref="authorSpaceEnvironmentName"/>
        <xs:element ref="orderSetFolderPath"/>
        <xs:element ref="softDeleted"/>
        <xs:element ref="createdDateTime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="documentId" type="xs:string"/>
  <xs:element name="version" type="xs:integer"/>
  <xs:element name="previousVersionId">
    <xs:complexType/>
  </xs:element>
  <xs:element name="nextVersionId">
    <xs:complexType/>
  </xs:element>
  <xs:element name="documentName" type="xs:string"/>
  <xs:element name="clientContentType" type="xs:NCName"/>
  <xs:element name="fileExtension" type="xs:NCName"/>
  <xs:element name="locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="uri"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="uri" type="xs:string"/>
  <xs:element name="userFirstName">
    <xs:complexType/>
  </xs:element>
  <xs:element name="userLastName">
    <xs:complexType/>
  </xs:element>
  <xs:element name="authorSpaceVersion">
    <xs:complexType/>
  </xs:element>
  <xs:element name="authorSpaceEnvironmentName">
    <xs:complexType/>
  </xs:element>
  <xs:element name="orderSetFolderPath">
    <xs:complexType/>
  </xs:element>
  <xs:element name="softDeleted" type="xs:boolean"/>
  <xs:element name="createdDateTime" type="xs:NMTOKEN"/>
</xs:schema>

=== iamomin/marklogic-data-analysis-tool/data/samples/clientContent.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientContent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clientContent.xsd">
  <documentId>76a3f4be-b9d6-44a1-a6a6-8f478821fca9</documentId>
  <version>1</version>
  <previousVersionId/>
  <nextVersionId/>
  <documentName>ORT Total Hip Replacement/Revision Post-Op - Adult</documentName>
  <clientContentType>uploadedPdf</clientContentType>
  <fileExtension>pdf</fileExtension>
  <locations>
    <uri>/env/1/clientContent/76a3f4be-b9d6-44a1-a6a6-8f478821fca9/uploadedPdf</uri>
  </locations>
  <userFirstName/>
  <userLastName/>
  <authorSpaceVersion/>
  <authorSpaceEnvironmentName/>
  <orderSetFolderPath/>
  <softDeleted>false</softDeleted>
  <createdDateTime>2013-05-03T11:34:00Z</createdDateTime>
</clientContent>
