=== iamomin/marklogic-data-analysis-tool/data/samples/iec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="iec">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="3">
        <xs:element name="comments" type="xs:string" minOccurs="0"/>
        <xs:element name="scopedIntervention">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="status" type="xs:string" />
        <xs:element name="inclusionCriteria" type="xs:string" minOccurs="0"/>
        <xs:element name="exclusionCriteria" type="xs:string" minOccurs="0"/>
        <xs:element name="drugClass" minOccurs="0"/>
        <xs:element name="testNotes" minOccurs="0"/>
        <xs:element name="pharmReview" minOccurs="0"/>
        <xs:element name="id" type="xs:string" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iamomin/marklogic-data-analysis-tool/data/samples/iec.xml
<?xml version="1.0" encoding="UTF-8"?>
<iec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="iec.xsd">
   <id>18d3bfc6-213b-428f-ab85-5358a446a34c</id>
   <inclusionCriteria>tsh, thyroid stimulating hormone, thyrotropin, TFT, thyroid function test, thyroid panel, thyroid profile</inclusionCriteria>
   <drugClass>n/a</drugClass>
   <status>released</status>
   <testNotes>2016-7-22 JP: duplicate</testNotes>
   <pharmReview>n/a</pharmReview>
   <comments>2018-1-29 JP: modified IC to include panel and profile
2016-7-22 JP: new SI, duplicate IEC</comments>
   <scopedIntervention>
      <id>8b10fe60-5822-48c7-9b34-bc220f1f5f02</id>
   </scopedIntervention>
</iec>
