=== iamomin/marklogic-data-analysis-tool/data/samples/performanceMeasure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="performanceMeasure">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="performanceMeasureName"/>
        <xs:element ref="legacyId"/>
        <xs:element ref="database"/>
        <xs:element ref="table"/>
        <xs:element ref="keyField"/>
        <xs:element ref="status"/>
        <xs:element ref="abbreviation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="id" type="xs:string"/>
  <xs:element name="performanceMeasureName" type="xs:string"/>
  <xs:element name="legacyId" type="xs:integer"/>
  <xs:element name="database" type="xs:NCName"/>
  <xs:element name="table" type="xs:NCName"/>
  <xs:element name="keyField" type="xs:NCName"/>
  <xs:element name="status" type="xs:NCName"/>
  <xs:element name="abbreviation" type="xs:string"/>
</xs:schema>

=== iamomin/marklogic-data-analysis-tool/data/samples/performanceMeasure.xml
<?xml version="1.0" encoding="UTF-8"?>
<performanceMeasure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="performanceMeasure.xsd">
  <id>12a87fe9-0ee7-4f60-badc-82817b8824fa</id>
  <performanceMeasureName>CMS National Hospital Inpatient Quality Measure</performanceMeasureName>
  <legacyId>25</legacyId>
  <database>eris</database>
  <table>quality_measures</table>
  <keyField>qmeasureid</keyField>
  <status>active</status>
  <abbreviation>CMS NHQM</abbreviation>
</performanceMeasure>
